### ISSUE TITLE
deer GBFS feed shows no vehicles available

### ISSUE THREAD

**Issue by ThorstenFroehlinghaus** [mobidata-bw/ipl-orchestration#132]
https://api.mobidata-bw.de/sharing/gbfs/deer/station_status shows for all stations `num_bikes_available=0` or `vehicle_types_available.count=0`. I checked the fleester API, but i cannot identify any differences in the `Locations` and `Vehicles` endpoints.

**Comment by hbruch** [comment]
The Fleetster bookings endpoint returns canceled bookings, which are not handled currently. As deer created blocking bookings for their fleet due to the planned provider switch, for nearly every vehicle such a booking starting from `"startDate": "2024-03-19T23:00:00.000Z"` to e.g.  `"endDate": "2024-10-01T16:53:00.000Z"` exists.

A booking have one of the following states:  canceled, created, expired, keyreleased, keyreturned, pending, rejected.

I suggest to ignore bookings in the states `canceled`,` rejected`, `keyreturned`. I'm not sure about `expired`. They might indicate late returns, where the booking ended already in the past, but the car is not yet available again(?).

**Comment by ThorstenFroehlinghaus** [comment]
I will ask deer about the meaning of this state.

**Comment by ThorstenFroehlinghaus** [comment]
Deer answered:
_expired/abgelaufen heißt, dass die Buchung nicht gestartet wurde. Man kann es auch interpretieren als "wurde vergessen zu stornieren".  Der Nutzer hatte also ein Fahrzeug gebucht und ist die Fahrt während der Buchungsdauer nicht angetreten / hat die Fahrt nicht gestartet._

As we discussed, the Deer x2bfs converter does not need to be changed.
